package com.kaemis.healthdesk.ui.strings

data class AppStrings(
    val dashboard: String,
    val focus: String,
    val reminders: String,
    val tasks: String,
    val stats: String,
    val profile: String,
    val settings: String,
    val openNavigationDrawer: String,
    val buyMeACoffee: String,
    val storedOnThisDevice: String,
    val welcomeBack: (String) -> String,
    val workingHoursEnabled: String,
    val workingHoursOff: String,
    val focusToday: String,
    val timerMode: (String) -> String,
    val modeSubtitle: (String) -> String,
    val workRestMinutes: (Int, Int) -> String,
    val focusTrackingPending: String,
    val focusActive: String,
    val focusIdle: String,
    val focusPaused: String,
    val focusAlarm: String,
    val restActive: String,
    val restPaused: String,
    val restAlarm: String,
    val snoozed: String,
    val completed: String,
    val stopped: String,
    val cyclesCompleteTitle: String,
    val cyclesCompleteMessage: (String) -> String,
    val start: String,
    val pause: String,
    val resume: String,
    val stop: String,
    val stopAlarm: String,
    val snooze: String,
    val startOutsideHoursTitle: String,
    val startOutsideHoursMessage: String,
    val startAnyway: String,
    val focusActual: (Long) -> String,
    val restActual: (Long) -> String,
    val snoozeCount: (Int) -> String,
    val todayFocusSummary: (Long, Int) -> String,
    val quickActions: String,
    val quickActionsPending: String,
    val addReminder: String,
    val reminderTitle: String,
    val iconLabel: String,
    val intervalLabel: String,
    val fixedTimeLabel: String,
    val recurringLabel: String,
    val everyMinutesLabel: String,
    val addIntervalReminder: String,
    val addFixedReminder: String,
    val addDailyReminder: String,
    val enabled: String,
    val disabled: String,
    val nextReminder: (String) -> String,
    val noReminders: String,
    val noRemindersDashboard: String,
    val newItem: String,
    val addTask: String,
    val taskTitle: String,
    val allCategories: String,
    val complete: String,
    val edit: String,
    val delete: String,
    val moveUp: String,
    val moveDown: String,
    val noTasks: String,
    val noTasksDashboard: String,
    val completedTasks: String,
    val focusMinutesToday: String,
    val sessionStats: String,
    val focusSessionsToday: String,
    val remindersToday: String,
    val sevenDayFocus: String,
    val sevenDayTasks: String,
    val taskDistribution: String,
    val recentCompletedTasks: String,
    val localProfileOnly: String,
    val displayName: String,
    val saveName: String,
    val chooseAvatar: String,
    val useInitialsAvatar: String,
    val support: String,
    val appearance: String,
    val theme: String,
    val system: String,
    val light: String,
    val dark: String,
    val accent: String,
    val sage: String,
    val mint: String,
    val amber: String,
    val clay: String,
    val sky: String,
    val lavender: String,
    val language: String,
    val appLanguage: String,
    val english: String,
    val spanish: String,
    val focusSession: String,
    val timerModeLabel: String,
    val focusModeName: String,
    val normal: String,
    val pomodoro: String,
    val multiCycle: String,
    val customModes: String,
    val newCustomMode: String,
    val pomodoroCycles: String,
    val pomodoroShortRest: String,
    val pomodoroLongRest: String,
    val multiCycleCycles: String,
    val cycleProgress: (Int, Int) -> String,
    val cyclePreviewLabel: String,
    val workMinutes: String,
    val restMinutes: String,
    val snoozeMinutes: String,
    val workingHours: String,
    val useWorkingHours: String,
    val startTime: String,
    val endTime: String,
    val allDay: String,
    val weeklyRuleEditingPending: String,
    val categories: String,
    val categoryManagementPending: String,
    val deleteCategoryMessage: String,
    val deleteTaskCategoryMessage: String,
    val notifications: String,
    val appNotifications: String,
    val notificationGuidancePending: String,
    val soundAndVibration: String,
    val haptics: String,
    val alarmSound: String,
    val reminderSound: String,
    val taskSound: String,
    val silent: String,
    val localData: String,
    val localDataPending: String,
    val exportJson: String,
    val shareExport: String,
    val importJson: String,
    val importBackupTitle: String,
    val importBackupMessage: (Int, Int, Int) -> String,
    val importBackup: String,
    val backupError: String,
    val resetLocalData: String,
    val resetLocalDataTitle: String,
    val resetLocalDataMessage: String,
    val cancel: String,
    val done: String,
    val reset: String,
    val aboutAndSupport: String,
    val versionText: String,
    val licenseText: String,
    val profileEditedFromProfile: String,
    val profileAvatarDescription: String,
    val placeholderDailyOverview: String,
    val placeholderFocusTitle: String,
    val placeholderRemindersTitle: String,
    val placeholderTasksTitle: String,
    val placeholderStatsTitle: String,
    val placeholderProfileTitle: String,
    val placeholderSettingsTitle: String,
    val placeholderDashboardBody: String,
    val placeholderFocusBody: String,
    val placeholderRemindersBody: String,
    val placeholderTasksBody: String,
    val placeholderStatsBody: String,
    val placeholderProfileBody: String,
    val placeholderSettingsBody: String,
)

fun stringsFor(languageCode: String): AppStrings = when (languageCode) {
    "es" -> spanishStrings
    else -> englishStrings
}

private val englishStrings = AppStrings(
    dashboard = "Dashboard",
    focus = "Focus",
    reminders = "Reminders",
    tasks = "Tasks",
    stats = "Stats",
    profile = "Profile",
    settings = "Settings",
    openNavigationDrawer = "Open navigation drawer",
    buyMeACoffee = "Buy me a coffee",
    storedOnThisDevice = "Stored on this device",
    welcomeBack = { name -> "Welcome back, $name" },
    workingHoursEnabled = "Working hours are enabled",
    workingHoursOff = "Working hours are off",
    focusToday = "Focus today",
    timerMode = { mode -> "Timer mode: $mode" },
    modeSubtitle = { mode -> "Mode: $mode" },
    workRestMinutes = { work, rest -> "Work $work min - Rest $rest min" },
    focusTrackingPending = "Focus session tracking will appear here when the timer phase is implemented.",
    focusActive = "Focus running",
    focusIdle = "Ready to focus",
    focusPaused = "Focus paused",
    focusAlarm = "Focus complete",
    restActive = "Rest running",
    restPaused = "Rest paused",
    restAlarm = "Rest complete",
    snoozed = "Snoozed",
    completed = "Completed",
    stopped = "Stopped",
    cyclesCompleteTitle = "Great work!",
    cyclesCompleteMessage = { mode -> "You completed every $mode cycle." },
    start = "Start",
    pause = "Pause",
    resume = "Resume",
    stop = "Stop",
    stopAlarm = "Stop alarm",
    snooze = "Snooze",
    startOutsideHoursTitle = "Start outside working hours?",
    startOutsideHoursMessage = "This session starts outside your configured working hours.",
    startAnyway = "Start anyway",
    focusActual = { seconds -> "Focus logged: ${seconds / 60} min" },
    restActual = { seconds -> "Rest logged: ${seconds / 60} min" },
    snoozeCount = { count -> "Snoozes: $count" },
    todayFocusSummary = { seconds, sessions -> "Today: ${seconds / 60} min across $sessions completed sessions" },
    quickActions = "Quick actions",
    quickActionsPending = "Start focus, add task and add reminder actions will be wired as each feature lands.",
    addReminder = "Add reminder",
    reminderTitle = "Reminder title",
    iconLabel = "Icon",
    intervalLabel = "Interval",
    fixedTimeLabel = "Fixed time",
    recurringLabel = "Recurring",
    everyMinutesLabel = "Every minutes",
    addIntervalReminder = "Add 30 min interval",
    addFixedReminder = "Add fixed 15:00",
    addDailyReminder = "Add daily 09:00",
    enabled = "Enabled",
    disabled = "Disabled",
    nextReminder = { value -> "Next: $value" },
    noReminders = "No reminders yet. Water is created by default and starts disabled.",
    noRemindersDashboard = "No reminders yet",
    newItem = "NEW",
    addTask = "Add task",
    taskTitle = "Task title",
    allCategories = "All",
    complete = "Complete",
    edit = "Edit",
    delete = "Delete",
    moveUp = "Up",
    moveDown = "Down",
    noTasks = "No pending tasks. Add one small next step.",
    noTasksDashboard = "No pending tasks",
    completedTasks = "Completed tasks",
    focusMinutesToday = "Focus minutes today",
    sessionStats = "Session stats",
    focusSessionsToday = "Focus sessions today",
    remindersToday = "Reminders today",
    sevenDayFocus = "7-day focus",
    sevenDayTasks = "7-day completed tasks",
    taskDistribution = "Tasks by category",
    recentCompletedTasks = "Recent completed tasks",
    localProfileOnly = "Local profile only. No account, no sync.",
    displayName = "Display name",
    saveName = "Save name",
    chooseAvatar = "Choose avatar",
    useInitialsAvatar = "Use initials avatar",
    support = "Support",
    appearance = "Appearance",
    theme = "Theme",
    system = "System",
    light = "Light",
    dark = "Dark",
    accent = "Accent",
    sage = "Sage",
    mint = "Mint",
    amber = "Amber",
    clay = "Clay",
    sky = "Sky",
    lavender = "Lavender",
    language = "Language",
    appLanguage = "App language",
    english = "English",
    spanish = "Spanish",
    focusSession = "Focus mode",
    timerModeLabel = "Timer mode",
    focusModeName = "Mode name",
    normal = "Normal",
    pomodoro = "Pomodoro",
    multiCycle = "Multi-cycle",
    customModes = "Custom modes",
    newCustomMode = "New custom mode",
    pomodoroCycles = "Pomodoro cycles",
    pomodoroShortRest = "Short rest minutes",
    pomodoroLongRest = "Long rest minutes",
    multiCycleCycles = "Multi-cycle rounds",
    cycleProgress = { current, total -> "Cycle $current of $total" },
    cyclePreviewLabel = "Cycle preview",
    workMinutes = "Work minutes",
    restMinutes = "Rest minutes",
    snoozeMinutes = "Snooze minutes",
    workingHours = "Working hours",
    useWorkingHours = "Use working hours",
    startTime = "Start",
    endTime = "End",
    allDay = "All day",
    weeklyRuleEditingPending = "Weekly rule editing will be added with the Focus timer phase.",
    categories = "Categories",
    categoryManagementPending = "Task and reminder category management will be added before Tasks and Reminders are completed.",
    deleteCategoryMessage = "Delete this category? Existing reminders will move to General.",
    deleteTaskCategoryMessage = "Delete this category? Existing tasks will move to General.",
    notifications = "Notifications",
    appNotifications = "App notifications",
    notificationGuidancePending = "Android permission and exact alarm guidance will appear here with notification scheduling.",
    soundAndVibration = "Sound and vibration",
    haptics = "Haptics",
    alarmSound = "Alarm sound",
    reminderSound = "Reminder sound",
    taskSound = "Task sound",
    silent = "Silent",
    localData = "Local data",
    localDataPending = "Export, import and reset stay local-only.",
    exportJson = "Export JSON",
    shareExport = "Share export",
    importJson = "Import JSON",
    importBackupTitle = "Import backup",
    importBackupMessage = { tasks, reminders, categories -> "This will replace local data with $tasks tasks, $reminders reminders and $categories categories." },
    importBackup = "Import",
    backupError = "Backup file is invalid or unsupported.",
    resetLocalData = "Reset local data",
    resetLocalDataTitle = "Reset local data?",
    resetLocalDataMessage = "This deletes the local profile, tasks, reminders, sessions, categories and settings, then recreates defaults. This cannot be undone.",
    cancel = "Cancel",
    done = "Done",
    reset = "Reset",
    aboutAndSupport = "About and support",
    versionText = "HealthDesk 1.0.0",
    licenseText = "License: GPL-3.0-or-later",
    profileEditedFromProfile = "Name and avatar are edited from the Profile screen.",
    profileAvatarDescription = "Profile avatar",
    placeholderDailyOverview = "Daily overview",
    placeholderFocusTitle = "Normal timer, Pomodoro and multi-cycle modes",
    placeholderRemindersTitle = "Water and custom wellness reminders",
    placeholderTasksTitle = "Simple categorized tasks",
    placeholderStatsTitle = "Local wellbeing stats",
    placeholderProfileTitle = "Local profile",
    placeholderSettingsTitle = "Live local settings",
    placeholderDashboardBody = "Focus, reminders and task summaries will appear here.",
    placeholderFocusBody = "The native timer will use durable alarms and a foreground service.",
    placeholderRemindersBody = "Recurring reminders will be scheduled with native Android alarms.",
    placeholderTasksBody = "Tasks stay lightweight and local-only, with customizable categories.",
    placeholderStatsBody = "Stats will be calculated from local sessions, tasks and reminder events.",
    placeholderProfileBody = "Name and avatar are stored only on this device.",
    placeholderSettingsBody = "Theme, accent, sounds, haptics and working hours are configured here.",
)

private val spanishStrings = AppStrings(
    dashboard = "Inicio",
    focus = "Enfoque",
    reminders = "Recordatorios",
    tasks = "Tareas",
    stats = "Estadísticas",
    profile = "Perfil",
    settings = "Ajustes",
    openNavigationDrawer = "Abrir menú de navegación",
    buyMeACoffee = "Invítame a un café",
    storedOnThisDevice = "Guardado en este dispositivo",
    welcomeBack = { name -> "Bienvenido de nuevo, $name" },
    workingHoursEnabled = "El horario laboral está activado",
    workingHoursOff = "El horario laboral está desactivado",
    focusToday = "Enfoque de hoy",
    timerMode = { mode -> "Modo de temporizador: $mode" },
    modeSubtitle = { mode -> "Modo: $mode" },
    workRestMinutes = { work, rest -> "Trabajo $work min - Descanso $rest min" },
    focusTrackingPending = "El seguimiento de sesiones aparecerá aquí cuando se implemente el temporizador.",
    focusActive = "Enfoque en curso",
    focusIdle = "Listo para enfocarte",
    focusPaused = "Enfoque pausado",
    focusAlarm = "Enfoque completado",
    restActive = "Descanso en curso",
    restPaused = "Descanso pausado",
    restAlarm = "Descanso completado",
    snoozed = "Aplazado",
    completed = "Completado",
    stopped = "Detenido",
    cyclesCompleteTitle = "¡Buen trabajo!",
    cyclesCompleteMessage = { mode -> "Has completado todos los ciclos de $mode." },
    start = "Iniciar",
    pause = "Pausar",
    resume = "Reanudar",
    stop = "Detener",
    stopAlarm = "Detener alarma",
    snooze = "Aplazar",
    startOutsideHoursTitle = "¿Iniciar fuera del horario laboral?",
    startOutsideHoursMessage = "Esta sesión empieza fuera de tu horario laboral configurado.",
    startAnyway = "Iniciar igualmente",
    focusActual = { seconds -> "Enfoque registrado: ${seconds / 60} min" },
    restActual = { seconds -> "Descanso registrado: ${seconds / 60} min" },
    snoozeCount = { count -> "Aplazamientos: $count" },
    todayFocusSummary = { seconds, sessions -> "Hoy: ${seconds / 60} min en $sessions sesiones completadas" },
    quickActions = "Acciones rápidas",
    quickActionsPending = "Las acciones para iniciar enfoque, añadir tarea y añadir recordatorio se conectarán con cada función.",
    addReminder = "Añadir recordatorio",
    reminderTitle = "Título del recordatorio",
    iconLabel = "Icono",
    intervalLabel = "Intervalo",
    fixedTimeLabel = "Hora fija",
    recurringLabel = "Recurrente",
    everyMinutesLabel = "Cada minutos",
    addIntervalReminder = "Añadir intervalo 30 min",
    addFixedReminder = "Añadir fijo 15:00",
    addDailyReminder = "Añadir diario 09:00",
    enabled = "Activado",
    disabled = "Desactivado",
    nextReminder = { value -> "Siguiente: $value" },
    noReminders = "No hay recordatorios todavía. Water se crea por defecto y empieza desactivado.",
    noRemindersDashboard = "No hay recordatorios todavía",
    newItem = "NUEVO",
    addTask = "Añadir tarea",
    taskTitle = "Título de la tarea",
    allCategories = "Todas",
    complete = "Completar",
    edit = "Editar",
    delete = "Eliminar",
    moveUp = "Subir",
    moveDown = "Bajar",
    noTasks = "No hay tareas pendientes. Añade un siguiente paso pequeño.",
    noTasksDashboard = "No hay tareas pendientes",
    completedTasks = "Tareas completadas",
    focusMinutesToday = "Minutos de enfoque hoy",
    sessionStats = "Estadísticas de sesión",
    focusSessionsToday = "Sesiones de enfoque hoy",
    remindersToday = "Recordatorios hoy",
    sevenDayFocus = "Enfoque de 7 días",
    sevenDayTasks = "Tareas completadas en 7 días",
    taskDistribution = "Tareas por categoría",
    recentCompletedTasks = "Tareas completadas recientes",
    localProfileOnly = "Perfil local. Sin cuenta y sin sincronización.",
    displayName = "Nombre visible",
    saveName = "Guardar nombre",
    chooseAvatar = "Elegir avatar",
    useInitialsAvatar = "Usar avatar con iniciales",
    support = "Soporte",
    appearance = "Apariencia",
    theme = "Tema",
    system = "Sistema",
    light = "Claro",
    dark = "Oscuro",
    accent = "Acento",
    sage = "Salvia",
    mint = "Menta",
    amber = "Ámbar",
    clay = "Arcilla",
    sky = "Cielo",
    lavender = "Lavanda",
    language = "Idioma",
    appLanguage = "Idioma de la app",
    english = "Inglés",
    spanish = "Español",
    focusSession = "Modo de enfoque",
    timerModeLabel = "Modo de temporizador",
    focusModeName = "Nombre del modo",
    normal = "Normal",
    pomodoro = "Pomodoro",
    multiCycle = "Multiciclo",
    customModes = "Modos personalizados",
    newCustomMode = "Nuevo modo personalizado",
    pomodoroCycles = "Ciclos Pomodoro",
    pomodoroShortRest = "Minutos de descanso corto",
    pomodoroLongRest = "Minutos de descanso largo",
    multiCycleCycles = "Rondas multiciclo",
    cycleProgress = { current, total -> "Ciclo $current de $total" },
    cyclePreviewLabel = "Vista previa del ciclo",
    workMinutes = "Minutos de trabajo",
    restMinutes = "Minutos de descanso",
    snoozeMinutes = "Minutos de aplazamiento",
    workingHours = "Horario laboral",
    useWorkingHours = "Usar horario laboral",
    startTime = "Inicio",
    endTime = "Fin",
    allDay = "Todo el día",
    weeklyRuleEditingPending = "La edición de reglas semanales se añadirá con el temporizador.",
    categories = "Categorías",
    categoryManagementPending = "La gestión de categorías de tareas y recordatorios se añadirá antes de completar Tareas y Recordatorios.",
    deleteCategoryMessage = "¿Eliminar esta categoría? Los recordatorios existentes se moverán a General.",
    deleteTaskCategoryMessage = "¿Eliminar esta categoría? Las tareas existentes se moverán a General.",
    notifications = "Notificaciones",
    appNotifications = "Notificaciones de la app",
    notificationGuidancePending = "La guía de permisos Android y alarmas exactas aparecerá con la programación de notificaciones.",
    soundAndVibration = "Sonido y vibración",
    haptics = "Háptica",
    alarmSound = "Sonido de alarma",
    reminderSound = "Sonido de recordatorio",
    taskSound = "Sonido de tarea",
    silent = "Silencio",
    localData = "Datos locales",
    localDataPending = "Exportar, importar y resetear se mantiene solo local.",
    exportJson = "Exportar JSON",
    shareExport = "Compartir export",
    importJson = "Importar JSON",
    importBackupTitle = "Importar backup",
    importBackupMessage = { tasks, reminders, categories -> "Esto reemplazará los datos locales con $tasks tareas, $reminders recordatorios y $categories categorías." },
    importBackup = "Importar",
    backupError = "El archivo de backup es inválido o no soportado.",
    resetLocalData = "Resetear datos locales",
    resetLocalDataTitle = "¿Resetear datos locales?",
    resetLocalDataMessage = "Esto elimina el perfil local, tareas, recordatorios, sesiones, categorías y ajustes, y recrea los valores por defecto. No se puede deshacer.",
    cancel = "Cancelar",
    done = "Hecho",
    reset = "Resetear",
    aboutAndSupport = "Acerca de y soporte",
    versionText = "HealthDesk 1.0.0",
    licenseText = "Licencia: GPL-3.0-or-later",
    profileEditedFromProfile = "El nombre y el avatar se editan desde la pantalla Perfil.",
    profileAvatarDescription = "Avatar del perfil",
    placeholderDailyOverview = "Resumen diario",
    placeholderFocusTitle = "Temporizador normal, Pomodoro y modos multiciclo",
    placeholderRemindersTitle = "Recordatorios de agua y bienestar",
    placeholderTasksTitle = "Tareas simples con categorías",
    placeholderStatsTitle = "Estadísticas locales de bienestar",
    placeholderProfileTitle = "Perfil local",
    placeholderSettingsTitle = "Ajustes locales en vivo",
    placeholderDashboardBody = "Aquí aparecerán los resúmenes de enfoque, recordatorios y tareas.",
    placeholderFocusBody = "El temporizador nativo usará alarmas duraderas y un servicio foreground.",
    placeholderRemindersBody = "Los recordatorios recurrentes se programarán con alarmas nativas de Android.",
    placeholderTasksBody = "Las tareas siguen siendo simples y locales, con categorías personalizables.",
    placeholderStatsBody = "Las estadísticas se calcularán desde sesiones, tareas y eventos de recordatorio locales.",
    placeholderProfileBody = "El nombre y el avatar se guardan solo en este dispositivo.",
    placeholderSettingsBody = "Tema, acento, sonidos, háptica y horario laboral se configuran aquí.",
)
